GET http://localhost:5000/categories

###
GET http://localhost:5000/categories/1

###

POST http://localhost:5000/categories
Content-Type: application/json

{
    "name": "Collections"
}

###

DELETE  http://localhost:5000/categories/13

###

PUT http://localhost:5000/categories/23
Content-Type: application/json

{
   "name": "VacationRental"
  
}

###

PATCH http://localhost:5000/categories/65
Content-Type: application/json

{
    "name": "qqch"
}